# --------------------------
# English language
# --------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1


# ------------------------------------------------------------
# German language
# ------------------------------------------------------------
[de]
languageName = "De"
languageCode = "de-DE"
contentDir = "content/german"
weight = 2
